# Generated by Django 4.2.4 on 2024-07-13 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_post',
            old_name='date_of_job_post',
            new_name='published_on',
        ),
    ]
