# Generated by Django 4.2.4 on 2024-07-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0004_rename_published_on_jobpost_job_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
