# Generated by Django 4.2.4 on 2024-10-26 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0005_alter_jobpost_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='is_payment_done',
            field=models.BooleanField(default=False),
        ),
    ]
