# Generated by Django 4.2.4 on 2024-10-27 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0006_jobpost_is_payment_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='job_post_type',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('premium', 'Premium'), ('hot_job', 'Hot_Job')], max_length=50, null=True),
        ),
    ]
