# Generated by Django 4.2.4 on 2024-10-27 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_post', '0007_jobpost_job_post_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='job_post_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('hot_job', 'Hot_Job')], default='standard', max_length=50),
        ),
    ]
