# Generated by Django 4.2.4 on 2024-07-13 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_seeker', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job_seeker',
            old_name='job_experience',
            new_name='experience',
        ),
    ]
