# Generated by Django 4.2.4 on 2024-10-28 07:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_post', '0008_alter_jobpost_job_post_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(max_length=100, unique=True)),
                ('val_id', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(max_length=10)),
                ('card_type', models.CharField(max_length=50)),
                ('card_brand', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_tran_id', models.CharField(blank=True, max_length=100, null=True)),
                ('store_id', models.CharField(max_length=100)),
                ('verify_sign', models.CharField(max_length=255)),
                ('tran_date', models.DateTimeField()),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='job_post.jobpost')),
            ],
        ),
    ]
