# Generated by Django 4.2.4 on 2024-07-13 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employer',
            name='user_type',
        ),
    ]
