# Generated by Django 4.2.4 on 2024-07-13 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job_post', '0005_alter_jobpost_salary'),
        ('job_seeker', '0002_rename_job_experience_job_seeker_experience'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='job_application/media/applications/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['doc', 'docx', 'pdf'], message='File type must be in pdf, doc or docx format.')])),
                ('salary', models.IntegerField()),
                ('applied_on', models.DateField(auto_now_add=True)),
                ('job_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisement', to='job_post.jobpost')),
                ('job_seeker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='job_seeker.job_seeker')),
            ],
            options={
                'unique_together': {('job_seeker', 'job_post')},
            },
        ),
    ]
