# Generated by Django 4.2.4 on 2024-07-15 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='jobapplication',
            unique_together=set(),
        ),
    ]
