# Generated by Django 4.2.4 on 2024-10-04 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_application', '0002_alter_jobapplication_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='resume',
        ),
    ]
